GET http://localhost:3000/api/players 
content-type: application/json


###
POST http://localhost:3000/api/players
content-type: application/json

    {
        "side": "forehand",
        "gender": "female",
        "level": "beginner"
    }

###
PUT http://localhost:3000/api/players/3
content-type: application/json

    {
        "id": 5,
        "side": "backhand",
        "gender": "female",
        "level": "advanced"
    }

###

DELETE http://localhost:3000/api/players/5
content-type: application/json

###

GET http://localhost:3000/api/players/
content-type: application/json

###
